const authActionTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_LOGIN_SUBMITTING: 'SET_LOGIN_SUBMITTING',
  SET_LOGIN_ERRORS: 'SET_LOGIN_ERRORS',
  SET_LOGIN_SUBMITTING_FALSE: 'SET_LOGIN_SUBMITTING_FALSE',
};

export default authActionTypes;
