const signUpAuthActionTypes = {
  SIGN_UP_AUTH: 'SIGN_UP_AUTH',
  SIGN_UP_AUTH_ERRORS: 'SIGN_UP_AUTH_ERRORS',
  SIGN_UP_AUTH_SUBMITTING: 'SIGN_UP_AUTH_SUBMITTING',
  RESET_SIGN_UP_AUTH_SUBMITTING: 'RESET_SIGN_UP_AUTH_SUBMITTING',
  CLEAR_AUTH_STATE: 'CLEAR_AUTH_STATE',
  RESEND_TOKEN: 'RESEND_TOKEN',
  RESENDING_TOKEN: 'RESENDING_TOKEN',
  RESET_RESENDING_TOKEN: 'RESET_RESENDING_TOKEN',
};

export default signUpAuthActionTypes;
