const signUpActionTypes = {
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_ERRORS: 'SIGN_UP_ERRORS',
  SIGN_UP_SUBMITTING: 'SIGN_UP_SUBMITTING',
  RESET_SIGN_UP_SUBMITTING: 'RESET_SIGN_UP_SUBMITTING',
  CLEAR_SIGN_UP: 'CLEAR_SIGN_UP',
};

export default signUpActionTypes;
